server:
  port: 8081

logging:
  level:
    root: info

bingconfig:
  proxy_address: ${PROXY-ADDRESS}
  proxy_port: ${PROXY-PORT}
  cookie: ${COOKIE}
spring:
  datasource:
    url: jdbc:mysql://${DB-HOST}/bing?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}
    hikari:
      max-lifetime: 120000
  config:
    import: .env.properties
